# Site settings
baseURL = "https://badacid.org"
languageCode = "en-US"
title = "BAD ACID"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "RSS", "sitemap"]
disableHugoGeneratorInject = true

# Local preview mode
relativeURLs = true
uglyURLs = true

# Copyright
copyright = "&copy;2024 Bad Acid"

[services]
  [services.googleAnalytics]
    # Enter your tracking code to enable Google Analytics
    ID = ""

[params]

  # Metadata for search engines and social sharing
  author = "Bad Acid"
  description = "A band from Austin, TX"
  shareImage = "images/Pyramid-512.png"
  twitterHandle = "tacoanthony"

  # Favicon
  favicon = "images/favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Music"

      [[params.links.list1.link]]
        text = "Listen"
        url = "https://open.spotify.com/artist/3cQUhWJrp5zmY6pEFXHRWB"
        new_tab = true # new tab

      [[params.links.list1.link]]
        text = "Watch"
        url = "https://www.youtube.com/watch?v=UIsQXWdXkfQ"
        new_tab = true # Default, open at same tab


  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://www.instagram.com/badacidatx/"

[server]
[[server.headers]]
    for = '/**'
    [server.headers.values]
      Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://dummyimage.com"
      Referrer-Policy = 'strict-origin-when-cross-origin'
      X-Content-Type-Options = 'nosniff'
      X-Frame-Options = 'DENY'
      X-XSS-Protection = '1; mode=block'
